UI skeleton and basic adding and removing bikes
io2-2021-wed-brodka/G_Admin pull request #1
Opened 2021-03-27 15:16 UTC by KrolikJakub

2021-03-27 15:30 UTC, arkadiusz-gorecki submitted a review, later dismissed
Bardzo fajne zmiany, dużo dodane.

2021-03-27 15:37 UTC, tomkarw requested changes
Prośba o drobne poprawki, bardziej stylistyka

2021-03-27 15:37 UTC, tomkarw commented on src/Api/ApiUtils.ts
> +            data: response.status!==204 ?await response.json() : null,
Musimy jakiś linter ustawić, tak żebyśmy zawsze mieli ładne formatowanie. Tutaj brakuje spacji po '?'

2021-03-27 15:37 UTC, tomkarw commented on src/Api/bikeApi.ts
> +    Working, InService,Blocked,
tutaj też spacji

2021-03-27 15:37 UTC, tomkarw commented on src/Api/bikeApi.ts
> +const target_url = BASE_URL + "bikes/"
nazwijmy to bikes_url, wynieśmy do src/Api/constants.ts

2021-03-27 15:37 UTC, tomkarw commented on src/Api/bikeApi.ts
> +    let url = target_url;
ta zmienna do wywalenia

2021-03-27 15:37 UTC, tomkarw commented on src/Api/bikeApi.ts
> +    return fetch(url,{
wtedy tutaj `bikes_url` zamaist `url`

2021-03-27 15:37 UTC, tomkarw commented on src/Api/bikeApi.ts
> +    let url = target_url + "getBikes";
tak samo jak wyżej

2021-03-27 15:37 UTC, tomkarw commented on src/App.tsx
> +          <Route path="/bikes">
`/bikes` i `/stations` wyniesione do constants, tutaj użycie zmiennych, tak jak gadaliśmy, żeby nie było literówek, i wystarczyło zmienić w jednym miejscu

2021-03-27 15:37 UTC, tomkarw commented on src/bikesList.tsx
> +  // bicycles.push({ID: 10,State: BikeState.Blocked,StationID: 22});
to do usunięcia :)

2021-03-27 15:37 UTC, tomkarw commented on src/bikesList.tsx
> +    const handleCloseSlidingWindow = () => {
chyba się formatowanie rozjechało, bo tutaj się dodatkowe spacje pojawiły

2021-03-27 15:37 UTC, tomkarw commented on src/bikesList.tsx
> +  const handleChange = (event: React.ChangeEvent<{ value: unknown }>) => {
nie wiadomo czego zmianę to handluje, zmień nazwę na `handleBikeStateChange` (jeśli dobrze rozumiem że to to robi)

2021-03-27 15:37 UTC, tomkarw commented on src/bikesList.tsx
> +      postBike({ID: Math.floor(Math.random() * 100), State: newBikeState, StationID: newBikeStationID}).then(r => {
przy postowaniu roweru nie potrzebujemy wysyłać `ID`, pogadamy jeszcze jak się to koszernie robi

2021-03-27 15:37 UTC, tomkarw commented on src/bikesList.tsx
> +                                  <option value={station.ID}> {station.ID} </option>
raczej chcemy podawać `station.name`, jeśli jeszcze nie mamy klasy `Station` na froncie to może tak chwilowo zostać, ale dodaj 
```
// TODO(krolikj): change to station.name once we add station functionality 
```
.

2021-03-27 15:37 UTC, tomkarw commented on src/bikesList.tsx
> +                              Do you really want you delete this group?
raczej `this bike`, pewnie zaszłość przy kopiowaniu

2021-03-27 19:46 UTC, linalenets submitted a review, later dismissed

2021-03-31 13:56 UTC, KrolikJakub commented on src/App.tsx
> +          <Route path="/bikes">
Strzele to kiedyś żeby teraz w tym githubie już sie nie bawic w takie spore zmiany

2021-03-31 15:16 UTC, arkadiusz-gorecki approved these changes

2021-03-31 16:18 UTC, linalenets approved these changes

2021-03-31 19:21 UTC, tomkarw approved these changes
Dzięki za poprawki. Spięcie z backendem zostawiamy na inny MR.

2021-03-31 19:21 UTC, merged