Feat/front back sync
io2-2021-wed-brodka/G_Admin pull request #4
Opened 2021-04-05 15:08 UTC by KrolikJakub

Wymiana wiadomości miedzy front i backendem

2021-04-06 13:41 UTC, tomkarw requested changes

2021-04-06 13:41 UTC, tomkarw commented on src/Api/bikeStationApi.ts
> +const target_url = BASE_URL + "stations/";
ta zmienna chyba do wywalenia, pod spodem jest identyczna

2021-04-06 13:41 UTC, tomkarw commented on src/bikesList.tsx
> +      postBike({id: 0, status: newBikestate, station: newBikestation}).then(r => {
możemy już wywalić to id?

2021-04-06 13:41 UTC, tomkarw commented on src/Api/bikeApi.ts
> +    id: number;
w związku z nowymi zmianami tu trzeba zmienić na string

2021-04-06 16:36 UTC, KrolikJakub commented on src/bikesList.tsx
> +      postBike({id: 0, status: newBikestate, station: newBikestation}).then(r => {
W tym miejscu jest tworzony obiekt, w zapytaniu wysyłana jest tylko potrzebna cześć. Można dodać oczywiście dodatkowy interfejs, ale nie wiem czy jest sens

2021-04-06 16:36 UTC, KrolikJakub commented on src/Api/bikeApi.ts
> +    id: number;
Zmienione -> ale nie działa, serwer django cały czas zwraca kod 500

2021-04-06 16:38 UTC, KrolikJakub commented on src/bikesList.tsx
> +      postBike({id: 0, status: newBikestate, station: newBikestation}).then(r => {
Jednak zmieniłem na przekazywanie samego stringa stacji

2021-04-06 17:34 UTC, tomkarw requested changes

2021-04-06 17:34 UTC, tomkarw commented on src/stationList.tsx
> +                          Station Location
Station Name

2021-04-06 17:34 UTC, tomkarw commented on src/stationList.tsx
> +                              Location
Name

2021-04-06 17:34 UTC, tomkarw commented on src/bikesList.tsx
> +                          <ListItemText primary={bike.station==null? "unsigned":"bike.station"} ></ListItemText>
interface Bike powinien raczej wyglądać tak:
```
export  interface Bike{
    id: string;
    status: BikeState;
    station?: { 
        id: string;
        name: string;
    };
  }
```
(zgodnie ze specyfikacją GET /bikes).
Wtedy tutaj możemy dać:
```
{bike.station==null? "" : bike.station.name }
```
(pusty string podoba mi się bardziej niż "unsigned", czy "moving", ale to już opinia).

2021-04-06 17:38 UTC, tomkarw requested changes

2021-04-06 17:38 UTC, tomkarw commented on src/bikesList.tsx
> +                          <ListItemText primary={bike.id} ></ListItemText>
Wywaliłbym całą kolumnę, ogólnie nie jest potrzebna, a przy id jako uuid to wgl krzak się robi

2021-04-07 07:38 UTC, tomkarw approved these changes

2021-04-07 07:49 UTC, arkadiusz-gorecki approved these changes

2021-04-07 07:49 UTC, arkadiusz-gorecki commented on src/Api/bikeApi.ts
> +  let res =  axios.delete(url).then(r=>axiosHandleResponse(r)).catch(()=>{console.log("error");});
Niepotrzebne przypisanie oraz chyba niepotrzebne wypisywanie informacji o błędzie na konsolę.

2021-04-07 07:54 UTC, tomkarw commented on src/Api/bikeApi.ts
> +  let res =  axios.delete(url).then(r=>axiosHandleResponse(r)).catch(()=>{console.log("error");});
To jest stara wersja pliku, jak ty to znalazłeś.
Obecnie jest tak:
```
export const deleteBike = async (bikeID: string) => {
    let delete_url = bikes_url + bikeID + '/';
    axios.delete(delete_url).then(r => axiosHandleResponse(r)).catch(() => {
        console.log("Error in deleteBike api call");
    });
}
```

2021-04-07 08:08 UTC, merged