Zmiana wyglądu aplikacji
io2-2021-wed-brodka/G_Admin pull request #8
Opened 2021-04-13 17:19 UTC by KrolikJakub

Pls, zaakceptować, można dodać do Jiry później opcje zmienia tego odświeżania, ale narazie niech działą jak jest

2021-04-13 17:27 UTC, tomkarw requested changes
Delay w kodzie nie przejdzie, to nie jest jakiś `must have`, możemy z tym poczekać.

2021-04-14 07:54 UTC, tomkarw requested changes

2021-04-14 07:54 UTC, tomkarw commented on src/Api/UserApi.ts
> +    role: UserRole;
tu jeszcze `username` będzie

2021-04-14 07:54 UTC, tomkarw commented on src/Api/ApiUtils.ts
> +export function delay(ms: number) {
usuń proszę te delay'e to to zmergujemy

2021-04-14 07:54 UTC, tomkarw commented on src/bikesList.tsx
> +            console.log(list);
to można usunąć

2021-04-14 08:26 UTC, tomkarw requested changes

2021-04-14 08:26 UTC, tomkarw commented on src/Api/bikeApi.ts
> +import {axiosHandleResponse, delay} from "./ApiUtils"
to działa jak usunałeś funkcję? i tak do wywalenia

2021-04-14 08:44 UTC, tomkarw approved these changes
Jest ok i ładne

2021-04-14 08:47 UTC, arkadiusz-gorecki approved these changes

2021-04-14 08:47 UTC, merged